name: Housing MLOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest tests -v

      - name: Train model
        run: |
          python -m src.train

      - name: Check model exists
        run: |
          ls -la

      - name: Build Docker image
        run: |
          docker build -t housing-fastapi .
      - name: Build Docker Image
        run: |
          docker build -t housing-fastapi .
